README.md
Hi, 
I have added my simple animation library like animated.css.
=> added styled-animated

README.md
Test utils for styled-components compatible with jest, expect, chai and jasmine
=> Added styled-components-test-utils

README.md
Here is a small component showing a date in the shape of a calendar icon. 
[Demo](https://react-calendar-icon-demo.now.sh)
[Repo](https://github.com/kkostov/react-calendar-icon)
=> Add react-calendar-icon to the list

README.md
https://github.com/kriasoft/react-static-boilerplate - a seed project for building pre-rendered single-page apps with Create React App, Relay Modern and Styled Components
=> Add react-static-boilerplate

README.md
Adds:
https://github.com/yldio/normalized-styled-components
https://github.com/yldio/styled-is
Thank you :)
=> Add styled-is and normalized-styled-components

README.md
[Razzle Material UI Styled Example](https://github.com/kireerik/razzle-material-ui-styled-example) - Razzle Material UI example with Styled Components using Express with compression.
=> Add Razzle Material UI Styled Example

README.md
=> Added RAN to boilerplate list

README.md
Removes duplicate "Getting Sassy wit styled-components" link.
=> Remove duplicate article

README.md
Add a timer project built with styled-components to the real apps list: https://github.com/Nargonath/getshitdone
Thanks for posting about this project on Twitter. :+1:
=> Add GetShitDone to real apps list

README.md
https://wuththelint.now.sh/
https://github.com/SaraVieira/styled-loaders
=> Add a website and a component

README.md
https://github.com/Monar/react-styled-box
https://www.npmjs.com/package/react-styled-box
=> Add react-styled-box

README.md
[Reactackle](https://github.com/bcrumbs/reactackle) is a set of components library built with styled-components.
=> Add Reactackle

README.md
~~Waiting to merge https://github.com/gitpoint/git-point/pull/495 this one before merging this change!~~
Thanks for creating this library, it's awesome!
=> Add GitPoint

README.md
Adds a link to shevyjs in the Helpers section of the README.
=> Update README Helpers with shevyjs

README.md
Proposal to add this util to the list.
https://github.com/RIP21/with-styled-class-names
Thanks.
=> Add to helpers list with-styled-class-names

README.md
=> add react-styled-flexbox to awesome styled components

README.md
Thank you, guys, for this awesome library! It would be an honour to be mentioned in the list... Thank you!
=> Add Count Minutes to Real Apps section

README.md
From their README:
>Sadly, this repository will no longer be maintained. The contributors are no longer able to devote time to managing an open source community
=> Remove unmaintained projects

README.md
Example of a real world React application using Styled Components.
=> Added Outline to real app category

README.md
=> Added styled-transition-group

README.md
I think this is a useful addition to the list because the Atlas is a fairly large (50k JS LOC) and popular (about 30000 visitors/month) application that shows how `styled-components` can be used at scale.
=> Add link and description of the Atlas of Economic Complexity

README.md
[React Starter Kit for Firebase](https://github.com/kriasoft/react-firebase-starter) ([demo](https://firebase.reactstarter.com/)) - ★ 3.2k
=> Add React Starter Kit, serverless edition with Styled Components

README.md
=> Add `react-microlink` component

README.md
added styled-bootstrap to the resources list
=> Add styled-bootstrap

README.md
=> Add "react-styled-select" component

README.md
=> Add styled-bootstrap-grid

README.md
=> Add Helsinki Food Guide to Real Apps

README.md
This package gives a non flexbox, deeply nestable, fluid and responsive grid option with some cool props to achieve things like vertically aligning content or reversing the order of the colums.
=> Add Styled-Grid-Responsive to list of grid options

README.md
=> Add rick-morty-app

README.md
=> Add react-rasta

README.md
Add [polished](https://github.com/styled-components/polished) to the helpers section of README.MD 😄 
=> Add polished to the 'helpers' section

README.md
=> Add tutorial for styled components

README.md
It would be great to be listed here. Thank you!
=> Add React Native Explorer to Real Apps section

README.md
https://github.com/leebenson/reactql -- or https://reactql.org for the full description
=> Adds ReactQL to 'boilerplates'

README.md
I have written an article on styled-components. This is in deep explanation of the library under the hood. Hope it is useful.
=> Add ref to How styled-components works

README.md
=> Add Smooth UI

README.md
=> Rename "reas" to "ReaKit"

README.md
Hi, I thought this live video course might be great add to the list of your video resources.
Please, let me know what you think about that.
Thank you for your consideration.
Rada.
=> video resources update

README.md
=> Add subatomic library

README.md
=> Add styled-reboot

README.md
=> Add styled-email-components

README.md
=> Add styled-react-modal

README.md
=> Epic spinner

README.md
Add styled-breakpoints in helpers list
=> Styled Breakpoints

README.md
Add Dutchie.com's usage of Styled Components.
=> Add Dutchie.com to Real Apps

README.md
=> Added more websites real apps list

README.md
=> Added Cloverleaf to list of real apps

README.md
=> add react-awesome-styled-grid

README.md
https://github.com/linonetwo/styled-tachyons
https://stackblitz.com/edit/react-hfstqe?file=index.js
=> Add styled-tachyons which make it conveient to use tachyons shorthands in sc

README.md
add [react-awesome-notifications](https://github.com/zakariaharti/react-awesome-notifications) to the Components section
=> add react-awesome-notifications

README.md
Hi :rocket:, I am happy to introduce our first GH project we've done with styled components. 
It is a community maintained ecosystem for those who want to stick it.
We expect to improve our documentation soon.
All the repository are using semantic-release, greenkeeper, and have code coverage on sonarcloud.
We'd like to add more tool for theming, and theme sharing (server), theme building, theme analysis. 
The ecosystem is working with redux, immutable, saga, and does not need to be a peer dependencies. 
It is also possible to use just the component you need.
Everyone can use the philosophy we wrote and profit from the well known Bootstrap base variables to create their ecosystem. 
We have @bootstrap-styled/v4 package that is the one with all the BS components, but that's not a requirement …
=> chore(readme): added bootstrap-styled to eco-system

README.md
=> add styled-media-helper

README.md
=> Add WebGazer to the Real Apps section.

README.md
=> Added grommet.io component library

README.md
=> Added sugUI Components Library

README.md
=> Added Orbit Components

README.md
=> Add jane to real apps section

README.md
To use the same description as in the package.json and on the repo
=> Update description of styled-reset

README.md
=> Add Styled-Container-Query

README.md
=> Adds SuperQuery to helpers section

README.md
=> Add spacing-helper to helpers section

README.md
---
<strong>Package:</strong> [react-functional-select](https://github.com/based-ghost/react-functional-select)
<strong>Reason for inclusion:</strong> It is a legitimate alternative to react-select in a fraction of the bundle size. It also is written entirely using `Hooks` & `FunctionComponents`, offers integrated virtualization via react-window, and is heavily optimized for performance.
=> Add react-functional-select to Components

README.md
=> add strapi admin panel to real apps category

contributing.md
=> fix broken link

README.md
=> add react-flex-ready to the components category

README.md
=> added React95 library to `components` section

README.md
=> doc: add "css-in-js-media" to helpers

README.md
* https://njt.now.sh
* https://github.com/kachkaev/njt
* https://twitter.com/kachkaev/status/1206204515126595586
---
~~Waiting for for Jan 2020 to publish this PR (project started on 2019-12-05)~~
=> Add njt (npm jump to) to Real Apps 🐸

README.md
=> Add styled-off-canvas to components category

README.md
Please consider including [Taskade](https://taskade.com)!  😃
=> Added Taskade 🐑 ✅

README.md
The project is newly added to github, but has been in development for 2 years privately.  We're now moving grape-ui to becoming an open source library.
=> added info about grape-ui.

README.md
=> Add PageXL to Real Apps section

README.md
=> Add react-raster to Grid Systems

README.md
=> Added react-styled-floating-label to the Components category

README.md
---
Hi 👋I'd like to add [Atomic Layout](https://github.com/kettanaito/atomic-layout) to the list of projects created with `styled-components`. I've added a concise description about the project, but if you would like to know more about it, please see my [talk at React Finland 2019](https://www.youtube.com/watch?v=_HrXUB97xQs), where I talk about the motivation and usage of the library.
=> Add Atomic Layout to Grid systems

README.md
—-
- [styled-react-boilerplate](https://github.com/xxczaki/styled-react-boilerplate)
=> Add styled-react-boilerplate

README.md
=> Add The Players Tribune to Real Apps

README.md
you can check package here [oah-ui](https://github.com/AhmedElywa/oah-ui) and [docs](http://oah-ui.ahmedelywa.com)
=> update readme: add oah-ui package

README.md
Hello, I have a React Table library built with styled-components that is starting to gain some traction and I thought it would be helpful for others to post it here.
=> Add react-data-table-component to components list

README.md
=> add bedrock layout primitives

README.md
=> Add Vimeo to real apps

README.md
=> Add Nyxo to real apps category

README.md
=> Add ThemeMiner

README.md
Client to generate styled components (including snapshot test and story book)
=> Add react-components-cli

README.md
**Here is the link to the GitHub repo for Earner (the newly added website to the Real App list):
https://github.com/Earner-ai/earner-website**
Earner is a React website using Styled-Components
=> Add Earner to the real apps category

README.md
If you want to see what MetaComponent does [try the REPL for styled-components](https://springload.github.io/metacomponent/#6).
It can help migrate sites to styled-components. You can paste in all your CSS, and write an HTML template format, and it will associate the CSS with the correct elements and generate components.
=> Add MetaComponent

README.md
Added a useful and thorough "tips and tricks" article.
This is my first ever PR - please let me know if I need to make changes.
=> Update README.md: Added article link
